export const jobBody = {
  type: 'object',
  additionalProperties: false,
  required: ['title', 'userId'],
  properties: {
    // title: { type: 'string' },
    // description: { type: 'string' },
    // descriptionCompany: { type: 'string' },
    // modelOfWork: { type: 'array' },
    // contractMode: { type: 'array' },
    // city: { type: 'string' },
    // state: { type: 'string' },
    // salary: { type: 'array' },
    // experience: { type: 'string' },
    // affirmative: { type: 'array' },
    // categories: { type: 'array' },
    // areas: { type: 'array' },
    // tags: { type: 'array' },
    // extra: { type: 'string' },
    // company: { type: 'string' },
    // phone: { type: 'string' },
    // email: { type: 'string' },
    // userId: { type: 'number' },
    // isActive: { type: 'boolean' },

    title: { type: 'string' },
    slug: { type: 'string' },
    description: { type: 'string' },
    descriptionCompany: { type: 'string' },
    modelOfWork: { type: 'array' },
    city: { type: 'string' },
    state: { type: 'string' },
    salary: { type: 'array' },
    tags: { type: 'array' },
    categories: { type: 'array' },
    affirmative: { type: 'array' },
    contractMode: { type: 'array' },
    travel: { type: 'array' },
    seniority: { type: 'array' },
    areas: { type: 'array' },
    extra: { type: 'string' },
    phone: { type: 'string' },
    email: { type: 'string' },
    company: { type: 'string' },
    isActive: { type: 'boolean' },
    showSalary: { type: 'boolean' },
    avatar: { type: 'string' },
    banner: { type: 'string' },
  },
};
export const jobBodyUpdate = {
  type: 'object',
  additionalProperties: false,
  required: ['id'],
  properties: {
    id: { type: 'number' },
    title: { type: 'string' },
    slug: { type: 'string' },
    description: { type: 'string' },
    descriptionCompany: { type: 'string' },
    modelOfWork: { type: 'array' },
    city: { type: 'string' },
    state: { type: 'string' },
    salary: { type: 'array' },
    tags: { type: 'array' },
    categories: { type: 'array' },
    affirmative: { type: 'array' },
    contractMode: { type: 'array' },
    seniority: { type: 'array' },
    travel: { type: 'array' },
    areas: { type: 'array' },
    extra: { type: 'string' },
    phone: { type: 'string' },
    email: { type: 'string' },
    company: { type: 'string' },
    isActive: { type: 'boolean' },
    showSalary: { type: 'boolean' },
    avatar: { type: 'string' },
    banner: { type: 'string' },
    // title: { type: 'string' },
    // slug: { type: 'string' },
    // description: { type: 'string' },
    // descriptionCompany: { type: 'string' },
    // modelOfWork: { type: 'array' },
    // contractMode: { type: 'array' },
    // city: { type: 'string' },
    // state: { type: 'string' },
    // showSalary: { type: 'boolean' },
    // salary: { type: 'array' },
    // experience: { type: 'string' },
    // affirmative: { type: 'array' },
    // categories: { type: 'array' },
    // areas: { type: 'array' },
    // tags: { type: 'array' },
    // extra: { type: 'string' },
    // company: { type: 'string' },
    // phone: { type: 'string' },
    // email: { type: 'string' },
    // userId: { type: 'number' },
    // isActive: { type: 'boolean' },
  },
};

export const getJobsQuerystring = {
  type: 'object',
  additionalProperties: false,
  required: ['limit', 'skip'],
  properties: {
    limit: {
      type: 'number',
    },
    skip: {
      type: 'number',
    },
  },
};

export const getJobsByUserQuerystring = {
  type: 'object',
  additionalProperties: false,
  required: ['userId', 'limit', 'skip'],
  properties: {
    userId: { type: 'number' },
    limit: {
      type: 'number',
    },
    skip: {
      type: 'number',
    },
  },
};
export const getJobsByUserSlugQuerystring = {
  type: 'object',
  additionalProperties: false,
  required: ['slug', 'limit', 'skip'],
  properties: {
    slug: { type: 'string' },
    limit: {
      type: 'number',
    },
    skip: {
      type: 'number',
    },
    isActive: {
      type: 'boolean',
    },
  },
};

export const relatedJobsBody = {
  type: 'object',
  additionalProperties: false,
  required: ['relatedJobIds', 'userId'],
  properties: {
    relatedJobIds: {
      type: 'string',
      items: {
        type: 'number',
      },
    },
    userId: {
      type: 'number',
    },
  },
};
